.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nestos-installer 8  "nestos-installer 0.20.0" 
.SH NAME
nestos\-installer\-iso\-reset \- Restore a nestos live ISO image to default settings
.SH SYNOPSIS
\fBnestos\-installer\-iso\-reset\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIISO\fR> 
.SH DESCRIPTION
Restore a nestos live ISO image to default settings
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIpath\fR
Write ISO to a new output file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fIISO\fR>
ISO image
.SH VERSION
v0.20.0
