.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nestos-installer 8  "nestos-installer 0.18.0" 
.SH NAME
nestos\-installer\-iso\-extract \- Commands to extract files from a nestos live ISO image
.SH SYNOPSIS
\fBnestos\-installer\-iso\-extract\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to extract files from a nestos live ISO image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
nestos\-installer\-iso\-extract\-pxe(8)
Extract PXE files from an ISO image
.TP
nestos\-installer\-iso\-extract\-minimal\-iso(8)
Extract a minimal ISO from a nestos live ISO image
.TP
nestos\-installer\-iso\-extract\-help(8)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.18.0
