.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nestos-installer 8  "nestos-installer 0.20.0" 
.SH NAME
nestos\-installer\-iso\-kargs \- Modify kernel args in a nestos live ISO image
.SH SYNOPSIS
\fBnestos\-installer\-iso\-kargs\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Modify kernel args in a nestos live ISO image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
nestos\-installer\-iso\-kargs\-modify(8)
Modify kernel args in an ISO image
.TP
nestos\-installer\-iso\-kargs\-reset(8)
Reset kernel args in an ISO image to defaults
.TP
nestos\-installer\-iso\-kargs\-show(8)
Show kernel args from an ISO image
.TP
nestos\-installer\-iso\-kargs\-help(8)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.20.0
