.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nestos-installer 8  "nestos-installer 0.20.0" 
.SH NAME
nestos\-installer\-iso \- Commands to manage a nestos live ISO image
.SH SYNOPSIS
\fBnestos\-installer\-iso\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to manage a nestos live ISO image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
nestos\-installer\-iso\-customize(8)
Customize a nestos live ISO image
.TP
nestos\-installer\-iso\-ignition(8)
Embed an Ignition config in a nestos live ISO image
.TP
nestos\-installer\-iso\-network(8)
Embed network settings in a nestos live ISO image
.TP
nestos\-installer\-iso\-kargs(8)
Modify kernel args in a nestos live ISO image
.TP
nestos\-installer\-iso\-extract(8)
Commands to extract files from a nestos live ISO image
.TP
nestos\-installer\-iso\-reset(8)
Restore a nestos live ISO image to default settings
.TP
nestos\-installer\-iso\-help(8)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.20.0
