.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nestos-installer 8  "nestos-installer 0.20.0" 
.SH NAME
nestos\-installer\-list\-stream \- List available images in a NestOS stream
.SH SYNOPSIS
\fBnestos\-installer\-list\-stream\fR [\fB\-s\fR|\fB\-\-stream\fR] [\fB\-\-stream\-base\-url\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
List available images in a NestOS stream
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-stream\fR=\fIname\fR [default: stable]
NestOS stream
.TP
\fB\-\-stream\-base\-url\fR=\fIURL\fR
Base URL for NestOS stream metadata
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.20.0
